# Site configuration

exclude:
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- .bundle
- .gem
- .jekyll-cache
- .ruby-version
- netlify.toml
- vendor

plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed

twitter:
  username: sfofgalaxy
author: Zifan
social:
  name: Zifan Peng
  links:
    - https://twitter.com/sfofgalaxy
    - https://www.linkedin.com/in/zifan-peng-968205219/
    - https://github.com/sfofgalaxy

sass:
  style: compressed
permalink: pretty
excerpt_separator: <!-- more -->
timezone: Asia/Beijing

collections:
  posts:
    title: Blog
    output: true
    description: "Research news, personal notes, publication reflections, and occasional writing"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page

encoding: utf-8
lang: en-GB
title: "Zifan Peng"
logo: "/assets/logos/logo.svg"
description: "Ph.D. Candidate in Financial Technology at HKUST (GZ), working on Trustworthy AI and DeFi & Blockchain."
url: "https://www.ziffer.top"
baseurl: ""
email: "sfofgalaxy[AT]gmail.com"

manifest:
  theme_color: "#f7f8f6"
  background_color: "#f7f8f6"

favicons:
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'

navigation_header:
- title: Home
  url: /
  icon: home
- title: Research
  url: /research/
  icon: research
- title: Blog
  url: /blog/
  icon: blog
