# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site favicons & manifest icons
# 9. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- .bundle
- .gem
- .jekyll-cache
- .ruby-version
- netlify.toml
- vendor
- archived

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed

# 3. Gem settings
twitter:
  username: sfofgalaxy # jekyll-seo-tag > Owners twitter username
author: Zifan # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Zifan Peng # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/sfofgalaxy
    - https://www.linkedin.com/in/zifan-peng-968205219/
    - https://github.com/sfofgalaxy
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Asia/Beijing # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Blog # Needed for Siteleaf
    output: true
    description: "Research news, personal notes, publication reflections, and occasional writing" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
      permalink: /blog/:year/:month/:day/:title/
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Zifan Peng" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Ph.D. Candidate in Financial Technology at HKUST (GZ), working on Trustworthy AI and DeFi & Blockchain." # Site description and default description, also used in jekyll-seo-tag
url: "https://www.ziffer.top" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/sfofgalaxy"
email: "sfofgalaxy[AT]gmail.com"
# date_format: "%-d %B %Y" # Post date formatting using placeholder formatting
# google_analytics: ""
# google_analytics_anonymize_ip: ""
# service_worker: false # Will turn off the service worker if set to false
# short_name: "Al" # The web application short name, defaults to the site title
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
manifest:
  theme_color: "#f7f8f6"
  background_color: "#f7f8f6"

# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'

# 9. Site navigation
navigation_header:
- title: Home
  url: /
  icon: home
- title: Research
  url: /research/
  icon: research
- title: Blog
  url: /blog/
  icon: blog
navigation_footer:
- title: Created by Zifan Peng
  url: /#

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/sfofgalaxy
  LinkedIn: https://www.linkedin.com/in/zifan-peng-968205219/
  GitHub: https://github.com/sfofgalaxy
  instagram: https://www.instagram.com/ziffer99/
  googlescholar: https://scholar.google.com/citations?user=2M8-SOwAAAAJ

sharing_links: {}
