source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "jekyll-sass-converter", "~> 2.2"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-redirect-from", "~> 0.16"
gem "base64", "~> 0.2"
gem "csv", "~> 3.3"
gem "ffi", "1.16.3"
gem "webrick", "~> 1.8"
